# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - test
test:
  image: node:latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: merry_test
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    DATABASE_CONNECTION: postgres://runner:@postgres:5432/merry_test
  stage: test
  tags: 
    - testing
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - npm --registry=https://registry.npm.taobao.org install 
    - npm test